### ISSUE TITLE
Usage instructions in README.md do not work 

### ISSUE THREAD

**Issue by afs25** [THIS-Institute/qualtrics-thiscovery-skin#3]
Instructions are to: 
"Run the dev script to get started (either with npm run dev or in your VDE of choice)."

That does not always work. Example:

```
hipc71:qualtrics-thiscovery-skin afs25$ npm run dev

> qualtrics-thiscovery-skin@2.1.0 dev
> DEBUG=thisco-dev node dev.2.js

internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'debug'
Require stack:
- /Users/afs25/GitHub/qualtrics-thiscovery-skin/dev.2.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/afs25/GitHub/qualtrics-thiscovery-skin/dev.2.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/afs25/GitHub/qualtrics-thiscovery-skin/dev.2.js' ]
}
```

Can we please add pre-requisite/dependencies instructions or troubleshooting info?

**Comment by afs25** [comment]
Ignore this. I am an idiot!
